---
- name: Install Docker
  hosts: all
  become: true
  vars_files:
    - vars.yml
  tasks:
    - name: Install apache2 package
      apt:
        name: "{{ package_name }}"
        state: present
        update_cache: true

    - name: Start and enable apache2 service
      service:
        name: "{{ package_name }}"
        state: started
        enabled: true